#!/bin/bash

echo "enter your Monthly Expences"

read -p "Rent" Rent
read -p "Utilities" Utilities
read -p "Gas" Gas
read -p "Food" Food
read -p "Others" Others

echo -e "(\nRent= $Rent,Utilities=$Utilities,Gas=$Gas,Food=$Food,Others=$Others)"

 
